# Generated by Django 6.1.dev20260220203023 on 2026-03-02 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='uploadDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.FileField(upload_to='pdfs')),
                ('photo', models.FileField(upload_to='photos')),
            ],
        ),
    ]
